<!DOCTYPE html >
<html lang="en">
<head >
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link rel="stylesheet" type="text/css" href="css/navigation.css">
	<link rel="stylesheet" href="style/slider-def.css">
	<link rel="stylesheet" type="text/css" href="sss/sss.css">
	<link href="http://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed|Alegreya:700" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<body>

	<header>
		<a href="index.php">
			<div class="scalable">
			<img src="images/logo.png" alt="dreamNOW">
			</div>
		</a>
	<!-- 	<h1>dreamNOW</h1>
		<h3>Realize your dream...</h3> -->
	</header>


<!-- 	UA-110392489-1 -->