<nav class="menu" id="myMenu">
	<ul>
	
		<li>
			<a href="index.php">Home</a>
		</li>
		<li>
			<a  href="aung-san-suu-kyi.php" >Aung San Suu Kyi</a>
		</li>
		<li>
			<a href="bill_gates.php">Bill Gates</a>
		</li>
		<li>
			<a href="gary_gygax.php">Gary Gygax</a>
		</li>

		<li>
			<a href="ada-lovelace.php">Ada Lovelace</a>
		</li>

		<li>
			<a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
		</li>

	</ul>
</nav>