
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
	<script src="sss/sss.min.js"></script>
	<script>
			$('.slider').sss({
				slideShow: true,
			});
	</script>
	<script src="js/menu-highlighter.js"></script>

		<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110392489-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-110392489-1');
	</script>

	<script>
		function myFunction() {
		    var x = document.getElementById("myMenu");
		    if (x.className === "menu") {
		        x.className += " responsive";
		    } else {
		        x.className = "menu";
		    }
		}
	</script>